src/java/com/demo/model/Persona.java

package com.demo.model;


public class Persona {
    
    private String Nombre;
    private String Apellido;
    private String Direccion;
    private String Sexo;
    private String Telefono;
    private int Codigo;
    
    
    public Persona (){}

        
    
    public String getNombre() {
        return Nombre;
    }

   
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    
    public String getApellido() {
        return Apellido;
    }

    
    public void setApellido(String Apellido) {
        this.Apellido = Apellido;
    }

    
    public String getDireccion() {
        return Direccion;
    }

   
    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }

   
    public String getSexo() {
        return Sexo;
    }

    public void setSexo(String Sexo) {
        this.Sexo = Sexo;
    }

    
    public String getTelefono() {
        return Telefono;
    }

    
    public void setTelefono(String Telefono) {
        this.Telefono = Telefono;
    }

    
    public int getCodigo() {
        return Codigo;
    }

    
    public void setCodigo(int Codigo) {
        this.Codigo = Codigo;
    }

    
    
    

    
}

src/java/com/demo/mb/personaMB.java

package com.demo.mb;

import com.demo.dao.personadao;
import com.demo.model.Persona;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;



@ManagedBean
@ViewScoped

public class personaMB {

    private Persona persona = new Persona();
   private List<Persona> lstpersonas;
   
    public personaMB() {
    }

    
    public Persona getPersona() {
        return persona;
    }

    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    
    public List<Persona> getLstpersonas() {
        return lstpersonas;
    }

    
    public void setLstpersonas(List<Persona> lstpersonas) {
        this.lstpersonas = lstpersonas;
    }
    
    
    
    
    
    
    //METODO REGISTRAR
    
    public void registrar() throws Exception {
        personadao dao;
    try{
    dao=new personadao();
    dao.registrar(persona);
    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,"REGISTRO EXITOSO!", "Contacto Guardado."));
    }catch(Exception e){
    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL,"ERROR!!", null));
    
    }finally {
    FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
    }
    }
    
    //...........................................
    
    
    //METODO LISTAR
    
    public void listar() throws Exception {
        personadao dao;
    try{
    dao=new personadao();
    lstpersonas=dao.listar();
    }catch(Exception e){
        throw e;
    
    }
    }
    
   //.................................................
    
    
    //METODO LEER
    
   public void readID(Persona per) throws Exception {
        personadao dao;
        Persona temporal;
    try{
    dao=new personadao();
    temporal = dao.readID(per);
    if(temporal != null){
    this.persona = temporal;
    }
    }catch(Exception e){
        throw e;
    
    }
     }
    
   //......................................................
    
   //METODO MODIFICAR
   
   public void modificar () throws Exception {
        personadao dao;
    try{
    dao=new personadao();
    dao.modificar(persona);
    this.listar();
    }catch(Exception e){
        throw e;
    
    }
    }
   //..................................................
   
   //METODO ELIMINAR
   public void eliminar(Persona per) throws Exception {
        personadao dao;
    try{
    dao=new personadao();
    dao.eliminar(per);
    this.listar();
    }catch(Exception e){
        throw e;
    
    }
    }
   
   //.......................................................
}

web/Administrar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>

        <ui:composition template="./layout/layout.xhtml">

            <ui:define name="top">                
            </ui:define>

            <ui:define name="content">
                
                <center> <h1> ADMINISTRAR CONTACTOS </h1> </center>
                
                <h:form id="frm">
                    <br/><br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <p:commandButton value="Administrar" actionListener="#{personaMB.listar()}" update="datatable" /> <br/><br/><br/>
                    
                    <p:dataTable id="datatable" value="#{personaMB.lstpersonas}" var="persona">
                        <p:column headerText="Nombre">
                            <p:outputLabel value="#{persona.nombre}"/>
                        </p:column>
                        <p:column headerText="Apellido">
                            <p:outputLabel value="#{persona.apellido}"/>
                        </p:column>
                        <p:column headerText="Sexo">
                            <p:outputLabel value="#{persona.sexo}"/>
                        </p:column>
                        <p:column headerText="Telefono">
                            <p:outputLabel value="#{persona.telefono}"/>
                        </p:column>
                        <p:column headerText="Direccion">
                            <p:outputLabel value="#{persona.direccion}"/>
                        </p:column>
                        <p:column headerText="Modificar">
                            <center> <p:commandButton icon="ui-icon-pencil" actionListener="#{personaMB.readID(persona)}" oncomplete="PF('dialogodatos').show();" update=":dialogoDatos" /></center>
                        </p:column>
                        <p:column headerText="Eliminar">
                            <center> <p:commandButton icon="ui-icon-closethick" actionListener="#{personaMB.eliminar(persona)}" update="datatable"/></center>
                        </p:column>
                                              
                    </p:dataTable>
                </h:form>
                
                
                
                <p:dialog header="DATOS" widgetVar="dialogodatos" id="dialogoDatos" showEffect="explode" hideEffect="bounce">
                    
                            <h:form>
                                
                <p:panelGrid columns="2">   
                    
                <p:outputLabel value="Nombre:" for="Nombre"/> 
                <p:inputText id="Nombre" size="30" maxlength="15" placeholder="Ingrese el Nombre" value="#{personaMB.persona.nombre}" /> 
               
                <p:outputLabel value="Apellido:" for="Apellido"/> 
                <p:inputText id="Apellido" size="30" maxlength="15" placeholder="Ingrese el Apellido" value="#{personaMB.persona.apellido}" />
                    
               <p:outputLabel value="Sexo:" for="Sexo"/> 
                <p:selectOneRadio id="Sexo" required="true" value="#{personaMB.persona.sexo}" >
                    <f:selectItem itemLabel="Masculino" itemValue="M"/>
                    <f:selectItem itemLabel="Femenino" itemValue="F"/>
                </p:selectOneRadio> 
                
                <p:outputLabel value="Telefono:" for="Telefono"/> 
                <p:inputText id="Telefono" size="30" maxlength="10" placeholder="Ingrese el Telefono" value="#{personaMB.persona.telefono}" />
                
                <p:outputLabel value="Direccion:" for="Direccion"/> 
                <p:inputText id="Direccion" size="30" maxlength="40" placeholder="Ingrese la Direccion" value="#{personaMB.persona.direccion}" />
                
                </p:panelGrid> <br/>
                
                <center>
                    <p:commandButton value="Modificar" actionListener="#{personaMB.modificar()}" oncomplete="PF('dialogodatos').hide();" update=":frm:datatable" /> &nbsp;
                     <p:commandButton value="Cancerlar" immediate="true" oncomplete="PF('dialogodatos').hide();" /></center>
                </h:form>
                            
                        </p:dialog>
                
                
            </ui:define>

        </ui:composition>

    </h:body>
</html>

web/Diagramas.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:body>

        <ui:composition template="./layout/layout.xhtml">

            <ui:define name="top">
                
            </ui:define>

            <ui:define name="content">
                
                
                <center> 
                    <h1>DIAGRAMAS DEL UML</h1> 
                    <br/><br/>
                    
                    <h2>DIAGRAMA DE CLASE</h2>
                    <br/><br/>
                    
                    <h:graphicImage value="resources/Imagenes/dc.png" width="600" height="300"/>
                    
                    <h2>DIAGRAMA DE CASOS DE USO</h2>
                    <br/><br/>
                    
                    <h:graphicImage value="resources/Imagenes/dcu.PNG" width="400" height="400"/></center>
                
                <br/><br/><br/><br/>
                <center> <h1>PATRONES DE DISEÑO</h1> </center><br/>
                
                <center> <h2>Patrón del filtro</h2><br/>
                <p> Es un patrón de diseño, mediante el cual, se permite filtrar una colección 
                    de objetos bajo diversos criterios.</p> <br/>
                    
                <h2>Patrón de la fachada</h2><br/>
                <p> patrón Fachada oculta las complejidades del sistema
                    y proporciona una interfaz para el cliente mediante
                    el cual el cliente puede acceder al sistema.</p> <br/>
                
                <h2>Patrón MVC</h2><br/>
                <p> El patrón de arquitectura MVC (Modelo Vista Controlador) es un patrón
                    que define la organización independiente del Modelo, 
                    la Vista (interfaz con el usuario u otro sistema) y el Controlador 
                    (controlador del workflow de la aplicación). <br/>

                    De esta forma, dividimos el sistema en tres capas donde, tenemos la encapsulación de los datos,
                    la interfaz o vista por otro y por último la lógica interna o controlador.</p>
                
                <br/> <p:commandButton value="Volver" action="index.jsf"/> <br/><br/><br/> </center>
            </ui:define>

        </ui:composition>

    </h:body>
</html>

web/Informacion.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:body>

        <ui:composition template="./layout/layout.xhtml">

            <ui:define name="top">
                
            </ui:define>

            <ui:define name="content">
                  
                <center> <h1> INFORMACION:</h1> </center>
                
                <center><p> 
                          
                        <br/> <h2> PRESENTADO POR: </h2> 
                        
                        Jhonnatan Smith Herrera Gonzalez
                        
                        <h2> PRESENTADO A: </h2>
                        
                        Alexander Jesus Osorio Barone 
                         
                        <h2> PROGRAMA: </h2> 
                        
                        Tecnologia en Desarrollo de Sistemas de Informacion 
                        
                       <h2> ASIGNATURA:</h2>
                        
                       Desarrollo de Software II
                       
                         <br/> <br/> 
                        <p:graphicImage value="resources/Imagenes/logoU.png" width="200" height="171"/>
                        
                       <h2>  PAIS/CUIDAD: </h2> 
                        Colombia - Cartagena
                        
                       <h2>  AÑO: </h2> 
                        
                              2016
                        
                    </p></center>
                
                
            </ui:define>

        </ui:composition>

    </h:body>
</html>

web/buscar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>

        <ui:composition template="./layout/layout.xhtml">

            <ui:define name="top">               
            </ui:define>

            <ui:define name="content">
                
                <h:form>
                    <center>  <h1>BUSCAR CONTACTOS</h1> </center>
                    
                     <br/><br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                   
                     <p:commandButton value="Listar" actionListener="#{personaMB.listar()}" update="data"/>
                                       
                     
                      <br/><br/><br/>
                     <p:dataTable id="data" value="#{personaMB.lstpersonas}" var="persona" >
                                                                              
                         
                         <p:column headerText="Nombre" filterBy="#{persona.nombre}" filterMatchMode="contains" >
                            <p:outputLabel value="#{persona.nombre}"/>
                        </p:column>
                        <p:column headerText="Apellido" filterBy="#{persona.apellido}" filterMatchMode="contains" >
                            <p:outputLabel value="#{persona.apellido}"/>
                        </p:column>
                        <p:column headerText="Sexo" filterBy="#{persona.sexo}" filterMatchMode="contains">
                            <p:outputLabel value="#{persona.sexo}"/>
                        </p:column>
                        <p:column headerText="Telefono" filterBy="#{persona.telefono}" filterMatchMode="contains">
                            <p:outputLabel value="#{persona.telefono}"/>
                        </p:column>
                        <p:column headerText="Direccion" filterBy="#{persona.direccion}" filterMatchMode="contains">
                            <p:outputLabel value="#{persona.direccion}"/>
                        </p:column>
                        
                    </p:dataTable>
                                   
                    
                </h:form>
                
                
                
                
            </ui:define>

        </ui:composition>

    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:body>

        <ui:composition template="./layout/layout.xhtml">
            
          <!-- Cabecera-->
            <ui:define name="top">                 
            </ui:define>
          <!-- Final Cabecera-->
          
          <!--Cuerpo-->
            <ui:define name="content">
                  
                  <center> <h1> Primer Parcial </h1> </center> 
                <br/>
                <center>
                    <p>
                        Realizar Aplicativo Web usando primefaces,
                        que permita administrar a una lista de contactos de un directorio web,
                        donde permita la búsqueda, según varios criterios, como nombre, correo, teléfono etc..
                    </p>
                
                <br/>
                <h:graphicImage value="resources/Imagenes/programacion.png" width="200" height="190"/>
                
               <h2>EJERCICIO:</h2>
              <h:graphicImage value="resources/Imagenes/a.png" width="50" height="50"/>
                </center> <br/>
                  
                
                <p:notificationBar position="top" effect="slide" styleClass="top" widgetVar="bar">
                
                <h:graphicImage value="resources/Imagenes/Bienvenido.png" width="180" height="100"/> &nbsp; &nbsp;
                <h:outputText value="BIENVENIDO!! " style="font-size:30px; color:black"  />
                </p:notificationBar> <center>
 
               <p:commandButton value="Show" onclick="PF('bar').show()" type="button" icon="ui-icon-arrow-1-s"/>
               <p:commandButton value="Hide" onclick="PF('bar').hide()" type="button" icon="ui-icon-arrow-1-n"/></center>
                
                
                
                
                
            </ui:define>
           <!--Final Cuerpo-->
        </ui:composition>

    </h:body>
</html>

web/layout/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Parcial</title> 
        
        <style> .Bimage{background-image:url("resources/Imagenes/fondo.png");}</style>
        
    </h:head>

    <h:body styleClass="Bimage">
       <!--cabecera--> 
        <div id="top" class="top">
            
            <ui:insert name="top">Top</ui:insert>
            <h:form>
            <p:megaMenu>  
               <p:menuitem value="Inicio" outcome="index.jsf"/>
                   
               <p:submenu label="Contactos">
                    <p:column>
                        <p:submenu label="Contactos">
                            <p:menuitem value="Registrar" outcome="registrar.jsf"/>
                            <p:menuitem value="Administrar" outcome="Administrar.jsf"/>                                                        
                        </p:submenu>
                    </p:column>
                    
                </p:submenu>
               
                <p:submenu label="Consultar"  >
                    <p:column>
                        <p:submenu label="Contactos" >
                            <p:menuitem value="Buscar" outcome="buscar.jsf"/>
                        </p:submenu>
                            
                    </p:column>
                    
                </p:submenu> 
               
                <p:submenu label="Informacion">
                    <p:column>
                        <p:submenu label="Presentado Por:"> 
                            <p:menuitem value="Jhonnatan S. Herrera G." outcome="Informacion.jsf"/>
                        </p:submenu>
                        <p:submenu label="Manual de Usuario">
                            <p:menuitem value="Ver" outcome="ManualUser.jsf"/>
                        </p:submenu>
                        <p:submenu label="Diagramas">
                            <p:menuitem value="Ver" outcome="Diagramas.jsf"/>                               
                                                        
                        </p:submenu>
                        
                    </p:column>
                    
                </p:submenu>
                
                
                
            </p:megaMenu></h:form>
            
        </div>
        <!--Fin de la cabecera--> 
        <!--cuerpo--> 
        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>
        <!-- Fin del cuerpo--> 
    </h:body>

</html>

web/registrar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>

        <ui:composition template="./layout/layout.xhtml">
            
           <!-- Cabecera-->
            <ui:define name="top">                
            </ui:define>
           <!--fin de la cabecera-->
           
           
           <!--cuerpo-->
            <ui:define name="content">
                
                <p:growl id="growl" autoUpdate="true" showDetail="true"  /> <br/>
                
                <center><h1>REGISTRO DE CONTACTO</h1></center>
                <!--Inicio del Formulario -->               
                <center><h:form id='form'> <br/><br/> <h:panelGrid columns="2">
                <p:outputLabel value="Nombre:" for="Nombre"/> 
                <p:inputText id="Nombre" size="30" maxlength="15" placeholder="Ingrese el Nombre" value="#{personaMB.persona.nombre}" required="true" requiredMessage="Campo Obligatorio. Ingrese el Nombre."/> 
               
                <p:outputLabel value="Apellido:" for="Apellido"/> 
                <p:inputText id="Apellido" size="30" maxlength="15" placeholder="Ingrese el Apellido" value="#{personaMB.persona.apellido}" required="true" requiredMessage="Campo Obligatorio. Ingrese el Apellido."/>
                    
                <p:outputLabel value="Telefono:" for="Telefono"/> 
                <p:inputText id="Telefono" size="30" maxlength="10" placeholder="Ingrese el Telefono" value="#{personaMB.persona.telefono}" required="true" requiredMessage="Campo Obligatorio. Ingrese el Telefono."/>
                
                <p:outputLabel value="Direccion:" for="Direccion"/> 
                <p:inputText id="Direccion" size="30" maxlength="40" placeholder="Ingrese la Direccion" value="#{personaMB.persona.direccion}" required="true" requiredMessage="Campo Obligatorio. Ingrese la Direccion."/>
                
                <p:outputLabel value="Sexo:" for="Sexo"/> 
                <p:selectOneRadio id="Sexo" required="true" value="#{personaMB.persona.sexo}" requiredMessage="Campo Obligatorio. Seleccione el Sexo.">
                    <f:selectItem itemLabel="Masculino" itemValue="M"/>
                    <f:selectItem itemLabel="Femenino" itemValue="F"/>
                </p:selectOneRadio> 
                                  
                                          
                <br/> <br/> 
                
                
                </h:panelGrid>     
                        &nbsp; &nbsp; <p:commandButton value="Guardar" actionListener="#{personaMB.registrar()}" action="registrar?faces-redirect=true" />
                </h:form></center> 
                <!-- Fin del formulario-->
                
            </ui:define>
            <!-- Fin del cuerpo -->
        </ui:composition>

    </h:body>
</html>